// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnEXjUrTJ72IbnsRH9GiLUdJi33yqpjN0',
    appId: '1:685264593642:web:b5c497e90ecd06f6faed93',
    messagingSenderId: '685264593642',
    projectId: 'inclusivelearningapp',
    authDomain: 'inclusivelearningapp.firebaseapp.com',
    storageBucket: 'inclusivelearningapp.firebasestorage.app',
    measurementId: 'G-X7TVSZ73WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAREGuUk6iBpmcS1u4tA9qVr9NykP-nnOc',
    appId: '1:685264593642:android:4a1027af3110b031faed93',
    messagingSenderId: '685264593642',
    projectId: 'inclusivelearningapp',
    storageBucket: 'inclusivelearningapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXfxmateYhspyYCk7xvnRg9H7txwAG5A0',
    appId: '1:685264593642:ios:b1705e8fe4259637faed93',
    messagingSenderId: '685264593642',
    projectId: 'inclusivelearningapp',
    storageBucket: 'inclusivelearningapp.firebasestorage.app',
    iosBundleId: 'com.example.inclusiveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXfxmateYhspyYCk7xvnRg9H7txwAG5A0',
    appId: '1:685264593642:ios:b1705e8fe4259637faed93',
    messagingSenderId: '685264593642',
    projectId: 'inclusivelearningapp',
    storageBucket: 'inclusivelearningapp.firebasestorage.app',
    iosBundleId: 'com.example.inclusiveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnEXjUrTJ72IbnsRH9GiLUdJi33yqpjN0',
    appId: '1:685264593642:web:530d8ad2a34a11d2faed93',
    messagingSenderId: '685264593642',
    projectId: 'inclusivelearningapp',
    authDomain: 'inclusivelearningapp.firebaseapp.com',
    storageBucket: 'inclusivelearningapp.firebasestorage.app',
    measurementId: 'G-EPSGE3EH6W',
  );
}
